"""
Django settings for game_store project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*t5#^e_p0e175!(8u7-753g3bxxt!do5qrd&v6p6_z-_(g_lkj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS define una lista de dominios o direcciones IP desde donde se permite acceder a esta aplicación Django. Es una medida de seguridad para evitar ataques como HTTP Host header attacks.
# En desarrollo, Django permite automáticamente 'localhost' y '127.0.0.1' caundo DEBUG es True, pero es buena práctica incluirlos explícitamente.
# Cuando se usa una herramienta como ngrok o se despliega la app en producción, también deben agregarse los dominios correspondientes.
ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    'c88a-200-85-189-33.ngrok-free.app'  # Dominio de ngrok
]

# Cuando usamos el dominio de ngrok y enviamos un formulario que contiene el "csrf_token" no va a devolver un error , para eso ponemos lo siguiente :
CSRF_TRUSTED_ORIGINS = [  
    "https://c88a-200-85-189-33.ngrok-free.app",
]
# Ese error se debe a que Django no confía en el origen (Origin) de la solicitud, que en este caso es tu URL de ngrok (https://6721-200-85-189-33.ngrok-free.app). Aunque hayas agregado esa URL en ALLOWED_HOSTS, también necesitás agregarla a la configuración de CSRF.

# Como uso ngrok : abro el ngrok.exe y corro ngrok http 8000 (8000 o el puerto donde este trabajando cuando hago el runserver)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "tienda",
    "usuarios",
    "carrito"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'game_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                BASE_DIR / 'templates_globales',  # Si tienes templates globales (opcional)
            ],
        'APP_DIRS': True, # APP_DIRS = True le indica a Django que busque templates dentro de una carpeta llamada templates en cada aplicación.
        'OPTIONS': {
            'context_processors': [   # context_processors : Es simplemente una función que recibe el request y devuelve un diccionario de variables que se inyectan automáticamente en cada contexto de plantilla.
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'carrito.context_processors.cant_productos_en_carrito', # Esto es la ruta completa a la función cant_productos_en_carrito dentro del proyecto, esto nos permite mostrar la cantiadad de productos que tiene el usuario en su carrito.              
            ],
        },
    },
]

WSGI_APPLICATION = 'game_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configuración para envío de correos reales (ejemplo con Gmail):
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'   # Con esto, el contenido del email se imprime en la consola, pero no se envía.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Si queremos que se envie ponemos este, ademas de agregar un email real.
EMAIL_HOST = 'smtp.gmail.com'  # Usamos el servidor SMTP de Gmail
EMAIL_PORT = 587 # El puerto para TLS (StartTLS)
EMAIL_USE_TLS = True # Habilita TLS (Transport Layer Security) para asegurar la conexión
EMAIL_HOST_USER = 'tiendagamestore3@gmail.com'
EMAIL_HOST_PASSWORD = 'dikfksuqhghawegx'  # Contraseña de aplicacion de google. (NO SUBIRLA AL GITHUB)
DEFAULT_FROM_EMAIL = 'Game Store <tiendagamestore3@gmail.com>'


# MercadoPago Config DE MI CUENTA:
# MERCADOPAGO_ACCESS_TOKEN = 'APP_USR-1472881132347913-062416-9ae621909862dbae04da8b8bf27403c2-462583124'  # (NO SUBIR AL GITHUB )
# MERCADOPAGO_PUBLIC_KEY = 'APP_USR-f3fd1320-3b03-4250-aa37-c781102034e0'  #(ESTE SE PUEDE SUBIR, PERO NO LO SUBAS IGUAL)

# MercadoPago Config de TESTEO :
MERCADOPAGO_ACCESS_TOKEN = 'APP_USR-7932180229049713-062714-469af90edbec483132cacccdc14a2273-2515054879'
MERCADOPAGO_PUBLIC_KEY = 'APP_USR-f67c0a27-fd6b-46da-b0f1-f6517627f21f'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es' # Al ponerlo en español , django ya traduce validaciones,etc automaticamente al español. ( Hay que agregar a los middleware esto : 'django.middleware.locale.LocaleMiddleware',)

# TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Definir la carpeta estática global
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static_global'),  # Carpeta estática global
]

AUTH_USER_MODEL = 'usuarios.CustomUser'   # Tabla/modelo dondes se guardaran los usuarios. La configuración AUTH_USER_MODEL le dice a Django que utilice un modelo de usuario personalizado en lugar del modelo predeterminado "User".


# Configuración para los archivos de medios
MEDIA_URL = '/media/'  # URL que usará el navegador para acceder a los archivos de medios

# Agregamos esto para que el login_required funcione correctamente :
LOGIN_URL = 'login'  # Definimos LOGIN_URL con la ruta asociada a "login" , para que cuando alguien quiera acceder a una ruta/vista en la que se requiere previamente estar logueado , te envie a la ruta/vista de "Iniciar Sesion".


# Directorio físico donde se guardarán los archivos de medios (especificamos la carpeta 'media')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
