"""
Django settings for game_store project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*t5#^e_p0e175!(8u7-753g3bxxt!do5qrd&v6p6_z-_(g_lkj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS define una lista de dominios o direcciones IP desde donde se permite acceder a esta aplicación Django. Es una medida de seguridad para evitar ataques como HTTP Host header attacks.
# En desarrollo, Django permite automáticamente 'localhost' y '127.0.0.1' caundo DEBUG es True, pero es buena práctica incluirlos explícitamente.
# Cuando se usa una herramienta como ngrok o se despliega la app en producción, también deben agregarse los dominios correspondientes.
ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    'c88a-200-85-189-33.ngrok-free.app'  # Tu dominio de ngrok
]

# Cuando usamos el dominio de ngrok y enviamos un formulario que contiene el "csrf_token" nos va a devolver un error , para eso ponemos lo siguiente :
CSRF_TRUSTED_ORIGINS = [  
    "https://c88a-200-85-189-33.ngrok-free.app", #Tu URL generada por ngrok
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "tienda",
    "usuarios",
    "carrito"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'game_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                BASE_DIR / 'templates_globales',  
            ],
        'APP_DIRS': True, 
        'OPTIONS': {
            'context_processors': [   
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'carrito.context_processors.cant_productos_en_carrito', 
            ],
        },
    },
]

WSGI_APPLICATION = 'game_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configuración para envío de correos reales (ejemplo con Gmail):
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'   # Con esto, el contenido del email se imprime en la consola, pero no se envía.
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Si queremos que se envie ponemos este, ademas de agregar un email real.
EMAIL_HOST = 'smtp.gmail.com'  # Usamos el servidor SMTP de Gmail
EMAIL_PORT = 587 # El puerto para TLS (StartTLS)
EMAIL_USE_TLS = True # Habilita TLS (Transport Layer Security) para asegurar la conexión
EMAIL_HOST_USER = 'tiendagamestore3@gmail.com' # Aca pone algun email
EMAIL_HOST_PASSWORD = ''  # Contraseña de ese email
DEFAULT_FROM_EMAIL = 'Game Store <tiendagamestore3@gmail.com>'


# MercadoPago Config de TESTEO :
MERCADOPAGO_ACCESS_TOKEN = '' # Aca deberia ir tu ACCESS_TOKEN real o uno de testo creado por vos
MERCADOPAGO_PUBLIC_KEY = '' # Y aca lo mismo pero con la PUBLIC_KEY

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Definir la carpeta estática global
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static_global'),  # Carpeta estática global
]

AUTH_USER_MODEL = 'usuarios.CustomUser'   


# Configuración para los archivos de medios
MEDIA_URL = '/media/'  

LOGIN_URL = 'login'  


# Directorio físico donde se guardarán los archivos de medios (especificamos la carpeta 'media')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
